// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class Professional
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int ProfId { get; set; }
        public string EnrollmentNum { get; set; }
        public string EnrollmentType { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public sbyte BillType { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}