// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entities.Models
{
    public partial class Shift
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int UserId { get; set; }
        public DateTime Date { get; set; }
        public DateTime UpdatedAt { get; set; }
        public sbyte Status { get; set; }

        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}